### PR TITLE
Updated code base to be compatible with the final FF API in Java22

### PR DESCRIPTION
**Pull request by hamid-nazari**
The title is self descriptive.
The latest release binaries fail to link against the final FF API in JDK22.
I've made little changes here and there to ensure compatibility and tested it on my own product which used old JNetPcap 1.4.

### CODE REVIEW

**Comment by arisona** [comment]
Thanks for creating this PR, I'm waiting to switch to JDK 22!

**Comment by arisona** [comment]
@hamid-nazari - I was in the meantime testing your changes for a small app on JDK 22. It works as expected, hope this will go into an official release soon!

**Comment by SecureNetWizard** [comment]
Checking the PR right now. I will update and release the 22 ASAP.

**Comment by SecureNetWizard** [comment]
Just a quick update. I'm still waiting in deployment "PENDING" mode, for Maven Central. As soon as it finishes, it should show up on central repo.

Maven dependency:
```
<!-- https://mvnrepository.com/artifact/com.slytechs.jnet.jnetpcap/jnetpcap-wrapper -->
<dependency>
    <groupId>com.slytechs.jnet.jnetpcap</groupId>
    <artifactId>jnetpcap-wrapper</artifactId>
    <version>2.2.0</version>
</dependency>
```

**Comment by SecureNetWizard** [comment]
Still waiting. I was hoping the new streamlined publishing system would be a lot quicker, but we get what we get:
Screenshot from 2024-06-25 16-19-03

**Comment by SecureNetWizard** [comment]
Everything finally resolved. The latest jnetpcap-wrapper is now live on central:

```
<!-- https://mvnrepository.com/artifact/com.slytechs.jnet.jnetpcap/jnetpcap-wrapper -->
<dependency>
    <groupId>com.slytechs.jnet.jnetpcap</groupId>
    <artifactId>jnetpcap-wrapper</artifactId>
    <version>2.2.1</version>
</dependency>
```

**Comment by SecureNetWizard** [comment]
One quick note. The issue is really resolved where now I will be posting regular updates. There is also a newer SNAPSHOT available, with major javadoc updates. Code changes are going to be minimal in the wrapper, but compatiblity and documentation will improve and be updated more frequently.

To add snapshots repository to your project:

```
<project>
  ...
  <repositories>
    <repository>
      <id>sonatype-snapshots</id>
      <name>Sonatype Snapshots</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>
  ...
</project>
```

**Pull request merged**
